"""Add subscription_tier

Revision ID: 2d8b3413d555
Revises: 002_generation_history
Create Date: 2026-01-01 20:10:21.262405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8b3413d555'
down_revision: Union[str, None] = '002_generation_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_generation_events_event_type'), table_name='generation_events')
    # op.drop_index(op.f('ix_generation_events_history_id'), table_name='generation_events')
    # op.drop_index(op.f('ix_generation_events_timestamp'), table_name='generation_events')
    # op.drop_index(op.f('ix_generation_history_post_id'), table_name='generation_history')
    # op.drop_index(op.f('ix_generation_history_started_at'), table_name='generation_history')
    # op.drop_index(op.f('ix_generation_history_status'), table_name='generation_history')
    # op.drop_index(op.f('ix_generation_history_user_id'), table_name='generation_history')
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=50), nullable=False, server_default='free'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    op.create_index(op.f('ix_generation_history_user_id'), 'generation_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_generation_history_status'), 'generation_history', ['status'], unique=False)
    op.create_index(op.f('ix_generation_history_started_at'), 'generation_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_generation_history_post_id'), 'generation_history', ['post_id'], unique=False)
    op.create_index(op.f('ix_generation_events_timestamp'), 'generation_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_generation_events_history_id'), 'generation_events', ['history_id'], unique=False)
    op.create_index(op.f('ix_generation_events_event_type'), 'generation_events', ['event_type'], unique=False)
    # ### end Alembic commands ###
