"""expand_brand_profile_fields

Revision ID: 8996a95fa9a7
Revises: 2d8b3413d555
Create Date: 2026-01-02 14:16:35.407987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8996a95fa9a7'
down_revision: Union[str, None] = '2d8b3413d555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_profiles', sa.Column('professional_title', sa.String(length=200), nullable=True))
    op.add_column('brand_profiles', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('brand_profiles', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('brand_profiles', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('brand_profiles', sa.Column('linkedin_profile_url', sa.Text(), nullable=True))
    op.add_column('brand_profiles', sa.Column('audience_pain_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('desired_outcome', sa.Text(), nullable=True))
    op.add_column('brand_profiles', sa.Column('expertise_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('writing_style', sa.String(length=50), nullable=True))
    op.add_column('brand_profiles', sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('words_to_use', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('words_to_avoid', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('sample_posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('primary_goal', sa.String(length=50), nullable=True))
    op.add_column('brand_profiles', sa.Column('posting_frequency', sa.String(length=50), nullable=True))
    op.add_column('brand_profiles', sa.Column('ideal_engagement_type', sa.String(length=50), nullable=True))
    op.add_column('brand_profiles', sa.Column('unique_story', sa.Text(), nullable=True))
    op.add_column('brand_profiles', sa.Column('unique_perspective', sa.Text(), nullable=True))
    op.add_column('brand_profiles', sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brand_profiles', sa.Column('personal_experiences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_generation_events_event_type'), table_name='generation_events')
    op.drop_index(op.f('ix_generation_events_history_id'), table_name='generation_events')
    op.drop_index(op.f('ix_generation_events_timestamp'), table_name='generation_events')
    op.drop_index(op.f('ix_generation_history_post_id'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_started_at'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_status'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_user_id'), table_name='generation_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_generation_history_user_id'), 'generation_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_generation_history_status'), 'generation_history', ['status'], unique=False)
    op.create_index(op.f('ix_generation_history_started_at'), 'generation_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_generation_history_post_id'), 'generation_history', ['post_id'], unique=False)
    op.create_index(op.f('ix_generation_events_timestamp'), 'generation_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_generation_events_history_id'), 'generation_events', ['history_id'], unique=False)
    op.create_index(op.f('ix_generation_events_event_type'), 'generation_events', ['event_type'], unique=False)
    op.drop_column('brand_profiles', 'personal_experiences')
    op.drop_column('brand_profiles', 'achievements')
    op.drop_column('brand_profiles', 'unique_perspective')
    op.drop_column('brand_profiles', 'unique_story')
    op.drop_column('brand_profiles', 'ideal_engagement_type')
    op.drop_column('brand_profiles', 'posting_frequency')
    op.drop_column('brand_profiles', 'primary_goal')
    op.drop_column('brand_profiles', 'sample_posts')
    op.drop_column('brand_profiles', 'words_to_avoid')
    op.drop_column('brand_profiles', 'words_to_use')
    op.drop_column('brand_profiles', 'personality_traits')
    op.drop_column('brand_profiles', 'writing_style')
    op.drop_column('brand_profiles', 'expertise_areas')
    op.drop_column('brand_profiles', 'desired_outcome')
    op.drop_column('brand_profiles', 'audience_pain_points')
    op.drop_column('brand_profiles', 'linkedin_profile_url')
    op.drop_column('brand_profiles', 'company_name')
    op.drop_column('brand_profiles', 'years_of_experience')
    op.drop_column('brand_profiles', 'industry')
    op.drop_column('brand_profiles', 'professional_title')
    # ### end Alembic commands ###
